"""empty message

Revision ID: 3bef7fc69d12
Revises: 696db92d0729
Create Date: 2018-11-15 18:44:24.022799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3bef7fc69d12'
down_revision = '696db92d0729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_column('category', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###
